In [1]:
# Dependencies and Setup
import pandas as pd
from pathlib import Path

# File to Load
census_data = Path("../datasets/age_census_data.csv")

In [2]:
# Load csv as df
census_df = pd.read_csv(census_data)

In [3]:
# View df
census_df.head()

,Label (Grouping),Alabama!!Total!!Estimate,Alabama!!Total!!Margin of Error,Alabama!!60 years and over!!Estimate,Alabama!!60 years and over!!Margin of Error,Alaska!!Total!!Estimate,Alaska!!Total!!Margin of Error,Alaska!!60 years and over!!Estimate,Alaska!!60 years and over!!Margin of Error,Arizona!!Total!!Estimate,...,Wisconsin!!60 years and over!!Estimate,Wisconsin!!60 years and over!!Margin of Error,Wyoming!!Total!!Estimate,Wyoming!!Total!!Margin of Error,Wyoming!!60 years and over!!Estimate,Wyoming!!60 years and over!!Margin of Error,Puerto Rico!!Total!!Estimate,Puerto Rico!!Total!!Margin of Error,Puerto Rico!!60 years and over!!Estimate,Puerto Rico!!60 years and over!!Margin of Error
0,Total population,"5,074,296",*****,"1,254,589","±8,153","733,583",*****,"145,091","±2,694","7,359,197",...,"1,526,889","±6,815","581,381",*****,"146,340","±2,749",NaN,NaN,NaN,NaN
1,SEX AND AGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Male,48.5%,±0.1,44.9%,±0.3,52.6%,±0.3,51.2%,±0.8,50.0%,...,47.3%,±0.2,51.2%,±0.4,49.1%,±0.9,NaN,NaN,NaN,NaN
3,Female,51.5%,±0.1,55.1%,±0.3,47.4%,±0.3,48.8%,±0.8,50.0%,...,52.7%,±0.2,48.8%,±0.4,50.9%,±0.9,NaN,NaN,NaN,NaN
4,Median age (years),39.6,±0.2,69.7,±0.2,35.9,±0.3,68.5,±0.4,38.8,...,69.6,±0.2,39.1,±0.5,69.5,±0.3,NaN,NaN,NaN,NaN

In [4]:
# Drop all columns with margin in name
census_df.drop(census_df.filter(regex='Margin').columns, axis=1, inplace=True)

# Drop 60+ columns
census_df.drop(census_df.filter(regex='60').columns, axis=1, inplace=True)
census_df.head()

,Label (Grouping),Alabama!!Total!!Estimate,Alaska!!Total!!Estimate,Arizona!!Total!!Estimate,Arkansas!!Total!!Estimate,California!!Total!!Estimate,Colorado!!Total!!Estimate,Connecticut!!Total!!Estimate,Delaware!!Total!!Estimate,District of Columbia!!Total!!Estimate,...,Tennessee!!Total!!Estimate,Texas!!Total!!Estimate,Utah!!Total!!Estimate,Vermont!!Total!!Estimate,Virginia!!Total!!Estimate,Washington!!Total!!Estimate,West Virginia!!Total!!Estimate,Wisconsin!!Total!!Estimate,Wyoming!!Total!!Estimate,Puerto Rico!!Total!!Estimate
0,Total population,"5,074,296","733,583","7,359,197","3,045,637","39,029,342","5,839,926","3,626,205","1,018,396","671,803",...,"7,051,339","30,029,572","3,380,800","647,064","8,683,619","7,785,786","1,775,156","5,892,539","581,381",NaN
1,SEX AND AGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Male,48.5%,52.6%,50.0%,49.4%,50.1%,50.7%,49.0%,48.6%,47.6%,...,49.1%,50.0%,50.8%,49.6%,49.5%,50.5%,49.7%,50.2%,51.2%,NaN
3,Female,51.5%,47.4%,50.0%,50.6%,49.9%,49.3%,51.0%,51.4%,52.4%,...,50.9%,50.0%,49.2%,50.4%,50.5%,49.5%,50.3%,49.8%,48.8%,NaN
4,Median age (years),39.6,35.9,38.8,38.9,37.9,37.7,40.9,41.5,34.9,...,39.2,35.6,32.1,43.2,39.0,38.4,42.9,40.4,39.1,NaN

In [5]:
# Rename the columns to be more readable 
#renamed_census_df = census_df.rename(columns=lambda x: x.replace('!!60 years and over!!Estimate', '_60+'))
renamed_census_df = census_df.rename(columns=lambda x: x.replace('!!Total!!Estimate', ''))
renamed_census_df = renamed_census_df.rename(columns={"Label (Grouping)": "State"})
renamed_census_df

,State,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,...,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Puerto Rico
0,Total population,"5,074,296","733,583","7,359,197","3,045,637","39,029,342","5,839,926","3,626,205","1,018,396","671,803",...,"7,051,339","30,029,572","3,380,800","647,064","8,683,619","7,785,786","1,775,156","5,892,539","581,381",NaN
1,SEX AND AGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Male,48.5%,52.6%,50.0%,49.4%,50.1%,50.7%,49.0%,48.6%,47.6%,...,49.1%,50.0%,50.8%,49.6%,49.5%,50.5%,49.7%,50.2%,51.2%,NaN
3,Female,51.5%,47.4%,50.0%,50.6%,49.9%,49.3%,51.0%,51.4%,52.4%,...,50.9%,50.0%,49.2%,50.4%,50.5%,49.5%,50.3%,49.8%,48.8%,NaN
4,Median age (years),39.6,35.9,38.8,38.9,37.9,37.7,40.9,41.5,34.9,...,39.2,35.6,32.1,43.2,39.0,38.4,42.9,40.4,39.1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122,GROSS RENT AS A PERCENTAGE OF HOUSEHOLD IN...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
123,Less than 30 percent,57.3%,60.7%,50.6%,59.6%,46.9%,49.1%,50.5%,55.2%,54.7%,...,55.9%,50.4%,55.0%,53.0%,53.7%,51.4%,58.2%,57.2%,61.4%,NaN
124,30 percent or more,42.7%,39.3%,49.4%,40.4%,53.1%,50.9%,49.5%,44.8%,45.3%,...,44.1%,49.6%,45.0%,47.0%,46.3%,48.6%,41.8%,42.8%,38.6%,NaN
125,GROSS RENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
126,Median gross rent (dollars),913,"1,329","1,450",846,"1,870","1,646","1,360","1,274","1,843",...,"1,096","1,290","1,372","1,141","1,441","1,630",795,992,895,NaN

In [6]:
# Filter out Puerto Rico data
renamed_census_df = renamed_census_df.drop(columns=['Puerto Rico'])
renamed_census_df

,State,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,...,South Dakota,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming
0,Total population,"5,074,296","733,583","7,359,197","3,045,637","39,029,342","5,839,926","3,626,205","1,018,396","671,803",...,"909,824","7,051,339","30,029,572","3,380,800","647,064","8,683,619","7,785,786","1,775,156","5,892,539","581,381"
1,SEX AND AGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Male,48.5%,52.6%,50.0%,49.4%,50.1%,50.7%,49.0%,48.6%,47.6%,...,50.8%,49.1%,50.0%,50.8%,49.6%,49.5%,50.5%,49.7%,50.2%,51.2%
3,Female,51.5%,47.4%,50.0%,50.6%,49.9%,49.3%,51.0%,51.4%,52.4%,...,49.2%,50.9%,50.0%,49.2%,50.4%,50.5%,49.5%,50.3%,49.8%,48.8%
4,Median age (years),39.6,35.9,38.8,38.9,37.9,37.7,40.9,41.5,34.9,...,38.5,39.2,35.6,32.1,43.2,39.0,38.4,42.9,40.4,39.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122,GROSS RENT AS A PERCENTAGE OF HOUSEHOLD IN...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
123,Less than 30 percent,57.3%,60.7%,50.6%,59.6%,46.9%,49.1%,50.5%,55.2%,54.7%,...,64.2%,55.9%,50.4%,55.0%,53.0%,53.7%,51.4%,58.2%,57.2%,61.4%
124,30 percent or more,42.7%,39.3%,49.4%,40.4%,53.1%,50.9%,49.5%,44.8%,45.3%,...,35.8%,44.1%,49.6%,45.0%,47.0%,46.3%,48.6%,41.8%,42.8%,38.6%
125,GROSS RENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
126,Median gross rent (dollars),913,"1,329","1,450",846,"1,870","1,646","1,360","1,274","1,843",...,866,"1,096","1,290","1,372","1,141","1,441","1,630",795,992,895

In [7]:
# Filter out the educational related rows
L = [37,38,39,40,41,42]
education_level = renamed_census_df.loc[L]
education_level

,State,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,...,South Dakota,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming
37,EDUCATIONAL ATTAINMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,Population 25 years and over,"3,474,924","489,218","5,053,656","2,057,624","26,866,773","4,084,004","2,545,188","724,041","479,231",...,"605,735","4,868,110","19,597,383","2,042,912","467,643","5,978,782","5,470,209","1,262,566","4,088,500","399,796"
39,Less than high school graduate,11.2%,6.7%,10.8%,10.9%,15.3%,7.0%,8.5%,8.0%,6.3%,...,6.8%,9.6%,13.9%,7.0%,5.0%,8.5%,7.8%,10.9%,6.5%,6.3%
40,"High school graduate, GED, or alternative",30.4%,29.1%,23.8%,34.3%,20.5%,20.2%,25.9%,28.2%,13.5%,...,29.2%,31.3%,24.2%,22.0%,26.0%,23.9%,21.5%,38.3%,29.6%,27.3%
41,Some college or associate's degree,29.6%,33.6%,32.4%,29.4%,27.2%,27.0%,23.7%,27.3%,14.8%,...,32.3%,28.0%,28.0%,33.1%,24.7%,25.4%,31.2%,26.0%,30.7%,36.9%
42,Bachelor's degree or higher,28.8%,30.6%,33.0%,25.4%,37.0%,45.9%,41.9%,36.5%,65.4%,...,31.6%,31.1%,33.9%,37.9%,44.2%,42.2%,39.5%,24.8%,33.2%,29.6%

In [8]:
# Flip the rows and columns and reset the index
education_level_flipped = education_level.set_index('State').transpose()
education_level_flipped

State,EDUCATIONAL ATTAINMENT,Population 25 years and over,Less than high school graduate,"High school graduate, GED, or alternative",Some college or associate's degree,Bachelor's degree or higher
Alabama,NaN,"3,474,924",11.2%,30.4%,29.6%,28.8%
Alaska,NaN,"489,218",6.7%,29.1%,33.6%,30.6%
Arizona,NaN,"5,053,656",10.8%,23.8%,32.4%,33.0%
Arkansas,NaN,"2,057,624",10.9%,34.3%,29.4%,25.4%
California,NaN,"26,866,773",15.3%,20.5%,27.2%,37.0%
Colorado,NaN,"4,084,004",7.0%,20.2%,27.0%,45.9%
Connecticut,NaN,"2,545,188",8.5%,25.9%,23.7%,41.9%
Delaware,NaN,"724,041",8.0%,28.2%,27.3%,36.5%
District of Columbia,NaN,"479,231",6.3%,13.5%,14.8%,65.4%
Florida,NaN,"16,104,410",10.1%,27.1%,28.6%,34.3%
Georgia,NaN,"7,332,980",10.5%,27.0%,27.8%,34.7%
Hawaii,NaN,"1,023,843",7.1%,26.8%,30.7%,35.4%
Idaho,NaN,"1,280,178",8.0%,26.0%,33.7%,32.3%
Illinois,NaN,"8,692,839",9.6%,25.2%,27.6%,37.7%
Indiana,NaN,"4,584,460",9.8%,32.1%,28.5%,29.6%
Iowa,NaN,"2,159,511",6.5%,29.5%,31.6%,32.3%
Kansas,NaN,"1,944,891",7.9%,25.3%,31.2%,35.6%
Kentucky,NaN,"3,091,499",11.0%,32.4%,28.7%,27.9%
Louisiana,NaN,"3,096,121",12.7%,32.5%,27.7%,27.1%
Maine,NaN,"1,030,141",5.4%,30.2%,28.4%,36.1%
Maryland,NaN,"4,286,216",8.6%,23.6%,24.0%,43.8%
Massachusetts,NaN,"4,947,384",8.7%,23.0%,21.7%,46.6%
Michigan,NaN,"6,978,952",8.2%,28.1%,31.6%,32.1%
Minnesota,NaN,"3,918,565",6.0%,23.4%,31.5%,39.1%
Mississippi,NaN,"1,963,322",12.4%,30.8%,32.1%,24.8%
Missouri,NaN,"4,236,010",8.4%,30.1%,29.2%,32.2%
Montana,NaN,"785,438",6.0%,27.7%,31.7%,34.6%
Nebraska,NaN,"1,300,094",7.2%,25.1%,33.1%,34.7%
Nevada,NaN,"2,223,852",12.6%,27.9%,32.5%,27.0%
New Hampshire,NaN,"1,024,780",5.5%,27.1%,26.1%,41.3%
New Jersey,NaN,"6,482,223",9.3%,25.2%,22.0%,43.5%
New Mexico,NaN,"1,453,129",12.0%,25.7%,31.8%,30.5%
New York,NaN,"13,892,241",12.1%,24.6%,23.3%,40.0%
North Carolina,NaN,"7,372,120",9.8%,24.9%,29.4%,35.9%
North Dakota,NaN,"514,786",6.1%,25.6%,36.4%,31.8%
Ohio,NaN,"8,130,929",8.2%,31.9%,27.8%,32.0%
Oklahoma,NaN,"2,661,141",10.4%,30.6%,30.5%,28.5%
Oregon,NaN,"3,043,930",8.4%,22.7%,32.6%,36.3%
Pennsylvania,NaN,"9,151,744",7.8%,33.0%,24.1%,35.1%
Rhode Island,NaN,"778,191",9.5%,24.7%,26.2%,39.6%
South Carolina,NaN,"3,664,922",9.5%,27.7%,30.2%,32.6%
South Dakota,NaN,"605,735",6.8%,29.2%,32.3%,31.6%
Tennessee,NaN,"4,868,110",9.6%,31.3%,28.0%,31.1%
Texas,NaN,"19,597,383",13.9%,24.2%,28.0%,33.9%
Utah,NaN,"2,042,912",7.0%,22.0%,33.1%,37.9%
Vermont,NaN,"467,643",5.0%,26.0%,24.7%,44.2%
Virginia,NaN,"5,978,782",8.5%,23.9%,25.4%,42.2%
Washington,NaN,"5,470,209",7.8%,21.5%,31.2%,39.5%
West Virginia,NaN,"1,262,566",10.9%,38.3%,26.0%,24.8%
Wisconsin,NaN,"4,088,500",6.5%,29.6%,30.7%,33.2%
Wyoming,NaN,"399,796",6.3%,27.3%,36.9%,29.6%

In [9]:
# Save .csv output
out_path = Path("../datasets/filtered_state_educational_data.csv")
education_level_flipped.to_csv(out_path)

In [10]:
# Get the unemployment data per state, by filtering out the unemployment rows
N = [77,78,79,80,81,82,83,84]
unemployment_data = renamed_census_df.loc[N]
unemployment_data

,State,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,...,South Dakota,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming
77,EMPLOYMENT STATUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,Population 16 years and over,"4,093,740","575,934","5,961,733","2,430,600","31,552,708","4,776,317","2,986,455","835,365","557,547",...,"716,965","5,699,603","23,471,441","2,560,844","548,050","7,041,278","6,328,051","1,466,266","4,802,830","465,883"
79,In labor force,58.6%,67.0%,60.7%,57.8%,63.9%,68.9%,65.7%,62.7%,71.8%,...,66.9%,62.4%,65.5%,70.0%,65.0%,65.3%,64.7%,52.8%,65.1%,65.8%
80,Civilian labor force,58.2%,62.8%,60.3%,57.5%,63.4%,67.9%,65.4%,62.4%,70.9%,...,66.2%,62.0%,65.0%,69.7%,64.7%,63.3%,63.7%,52.7%,65.0%,64.9%
81,Employed,55.7%,59.9%,57.7%,54.9%,60.0%,65.6%,62.3%,59.7%,67.2%,...,64.3%,59.9%,62.1%,67.8%,62.8%,61.0%,61.1%,50.2%,63.2%,62.5%
82,Unemployed,2.5%,2.9%,2.6%,2.6%,3.4%,2.4%,3.1%,2.7%,3.6%,...,1.9%,2.1%,2.9%,1.9%,1.8%,2.3%,2.6%,2.5%,1.8%,2.4%
83,Percent of civilian labor ...,4.3%,4.6%,4.3%,4.5%,5.3%,3.5%,4.7%,4.3%,5.1%,...,2.8%,3.4%,4.4%,2.7%,2.8%,3.6%,4.1%,4.7%,2.8%,3.8%
84,Armed forces,0.4%,4.2%,0.4%,0.3%,0.5%,0.9%,0.2%,0.4%,0.9%,...,0.8%,0.4%,0.5%,0.3%,0.3%,2.0%,1.0%,0.2%,0.1%,0.9%

In [15]:
# Flip the rows and columns and reset the index
unemployment_data_flipped = unemployment_data.set_index('State').transpose()
unemployment_data_flipped

State,EMPLOYMENT STATUS,Population 16 years and over,In labor force,Civilian labor force,Employed,Unemployed,Percent of civilian labor force,Armed forces
Alabama,NaN,"4,093,740",58.6%,58.2%,55.7%,2.5%,4.3%,0.4%
Alaska,NaN,"575,934",67.0%,62.8%,59.9%,2.9%,4.6%,4.2%
Arizona,NaN,"5,961,733",60.7%,60.3%,57.7%,2.6%,4.3%,0.4%
Arkansas,NaN,"2,430,600",57.8%,57.5%,54.9%,2.6%,4.5%,0.3%
California,NaN,"31,552,708",63.9%,63.4%,60.0%,3.4%,5.3%,0.5%
Colorado,NaN,"4,776,317",68.9%,67.9%,65.6%,2.4%,3.5%,0.9%
Connecticut,NaN,"2,986,455",65.7%,65.4%,62.3%,3.1%,4.7%,0.2%
Delaware,NaN,"835,365",62.7%,62.4%,59.7%,2.7%,4.3%,0.4%
District of Columbia,NaN,"557,547",71.8%,70.9%,67.2%,3.6%,5.1%,0.9%
Florida,NaN,"18,459,053",59.6%,59.2%,56.8%,2.4%,4.0%,0.4%
Georgia,NaN,"8,708,310",63.9%,63.2%,60.6%,2.6%,4.2%,0.7%
Hawaii,NaN,"1,175,667",63.5%,59.5%,57.4%,2.2%,3.6%,3.9%
Idaho,NaN,"1,530,729",62.4%,62.0%,60.2%,1.8%,3.0%,0.4%
Illinois,NaN,"10,199,598",65.0%,64.8%,61.7%,3.1%,4.8%,0.2%
Indiana,NaN,"5,456,066",63.9%,63.8%,61.5%,2.3%,3.6%,0.1%
Iowa,NaN,"2,570,925",66.6%,66.5%,64.5%,2.0%,2.9%,0.2%
Kansas,NaN,"2,330,842",65.7%,64.8%,62.5%,2.4%,3.6%,0.8%
Kentucky,NaN,"3,626,511",59.9%,59.4%,56.8%,2.6%,4.3%,0.4%
Louisiana,NaN,"3,656,541",59.4%,58.9%,55.7%,3.2%,5.4%,0.5%
Maine,NaN,"1,170,061",61.7%,61.5%,59.5%,2.0%,3.3%,0.2%
Maryland,NaN,"4,974,349",67.0%,66.3%,63.7%,2.6%,4.0%,0.7%
Massachusetts,NaN,"5,805,465",66.8%,66.7%,64.0%,2.7%,4.1%,0.1%
Michigan,NaN,"8,179,427",61.6%,61.5%,58.7%,2.9%,4.6%,0.1%
Minnesota,NaN,"4,579,443",68.0%,67.9%,65.7%,2.2%,3.2%,0.1%
Mississippi,NaN,"2,341,292",57.1%,56.5%,53.7%,2.8%,4.9%,0.6%
Missouri,NaN,"4,974,792",62.8%,62.4%,60.1%,2.3%,3.7%,0.5%
Montana,NaN,"916,289",63.5%,63.0%,61.1%,1.9%,3.0%,0.5%
Nebraska,NaN,"1,547,790",68.3%,67.8%,66.2%,1.6%,2.3%,0.5%
Nevada,NaN,"2,572,023",63.3%,62.7%,59.3%,3.4%,5.5%,0.6%
New Hampshire,NaN,"1,177,400",65.8%,65.7%,64.0%,1.7%,2.5%,0.1%
New Jersey,NaN,"7,510,983",66.2%,66.0%,62.7%,3.3%,5.0%,0.2%
New Mexico,NaN,"1,710,459",58.5%,57.5%,54.8%,2.8%,4.8%,1.0%
New York,NaN,"16,154,241",62.8%,62.6%,59.4%,3.2%,5.1%,0.2%
North Carolina,NaN,"8,671,939",62.8%,61.5%,59.2%,2.3%,3.8%,1.3%
North Dakota,NaN,"617,710",68.7%,67.6%,66.1%,1.5%,2.2%,1.1%
Ohio,NaN,"9,506,533",63.1%,63.0%,60.6%,2.3%,3.7%,0.2%
Oklahoma,NaN,"3,178,852",61.0%,60.3%,57.8%,2.5%,4.2%,0.8%
Oregon,NaN,"3,509,464",62.4%,62.4%,59.7%,2.7%,4.3%,0.1%
Pennsylvania,NaN,"10,660,341",62.8%,62.8%,60.1%,2.7%,4.3%,0.1%
Rhode Island,NaN,"916,019",64.6%,64.1%,61.2%,2.9%,4.5%,0.5%
South Carolina,NaN,"4,294,594",60.7%,59.7%,57.1%,2.6%,4.4%,1.0%
South Dakota,NaN,"716,965",66.9%,66.2%,64.3%,1.9%,2.8%,0.8%
Tennessee,NaN,"5,699,603",62.4%,62.0%,59.9%,2.1%,3.4%,0.4%
Texas,NaN,"23,471,441",65.5%,65.0%,62.1%,2.9%,4.4%,0.5%
Utah,NaN,"2,560,844",70.0%,69.7%,67.8%,1.9%,2.7%,0.3%
Vermont,NaN,"548,050",65.0%,64.7%,62.8%,1.8%,2.8%,0.3%
Virginia,NaN,"7,041,278",65.3%,63.3%,61.0%,2.3%,3.6%,2.0%
Washington,NaN,"6,328,051",64.7%,63.7%,61.1%,2.6%,4.1%,1.0%
West Virginia,NaN,"1,466,266",52.8%,52.7%,50.2%,2.5%,4.7%,0.2%
Wisconsin,NaN,"4,802,830",65.1%,65.0%,63.2%,1.8%,2.8%,0.1%
Wyoming,NaN,"465,883",65.8%,64.9%,62.5%,2.4%,3.8%,0.9%

In [20]:
# unemployment_data_flipped['index'] = range(1, len(unemployment_data_flipped) + 1)
# unemployment_data_flipped

State,EMPLOYMENT STATUS,Population 16 years and over,In labor force,Civilian labor force,Employed,Unemployed,Percent of civilian labor force,Armed forces,index
Alabama,NaN,"4,093,740",58.6%,58.2%,55.7%,2.5%,4.3%,0.4%,1
Alaska,NaN,"575,934",67.0%,62.8%,59.9%,2.9%,4.6%,4.2%,2
Arizona,NaN,"5,961,733",60.7%,60.3%,57.7%,2.6%,4.3%,0.4%,3
Arkansas,NaN,"2,430,600",57.8%,57.5%,54.9%,2.6%,4.5%,0.3%,4
California,NaN,"31,552,708",63.9%,63.4%,60.0%,3.4%,5.3%,0.5%,5
Colorado,NaN,"4,776,317",68.9%,67.9%,65.6%,2.4%,3.5%,0.9%,6
Connecticut,NaN,"2,986,455",65.7%,65.4%,62.3%,3.1%,4.7%,0.2%,7
Delaware,NaN,"835,365",62.7%,62.4%,59.7%,2.7%,4.3%,0.4%,8
District of Columbia,NaN,"557,547",71.8%,70.9%,67.2%,3.6%,5.1%,0.9%,9
Florida,NaN,"18,459,053",59.6%,59.2%,56.8%,2.4%,4.0%,0.4%,10
Georgia,NaN,"8,708,310",63.9%,63.2%,60.6%,2.6%,4.2%,0.7%,11
Hawaii,NaN,"1,175,667",63.5%,59.5%,57.4%,2.2%,3.6%,3.9%,12
Idaho,NaN,"1,530,729",62.4%,62.0%,60.2%,1.8%,3.0%,0.4%,13
Illinois,NaN,"10,199,598",65.0%,64.8%,61.7%,3.1%,4.8%,0.2%,14
Indiana,NaN,"5,456,066",63.9%,63.8%,61.5%,2.3%,3.6%,0.1%,15
Iowa,NaN,"2,570,925",66.6%,66.5%,64.5%,2.0%,2.9%,0.2%,16
Kansas,NaN,"2,330,842",65.7%,64.8%,62.5%,2.4%,3.6%,0.8%,17
Kentucky,NaN,"3,626,511",59.9%,59.4%,56.8%,2.6%,4.3%,0.4%,18
Louisiana,NaN,"3,656,541",59.4%,58.9%,55.7%,3.2%,5.4%,0.5%,19
Maine,NaN,"1,170,061",61.7%,61.5%,59.5%,2.0%,3.3%,0.2%,20
Maryland,NaN,"4,974,349",67.0%,66.3%,63.7%,2.6%,4.0%,0.7%,21
Massachusetts,NaN,"5,805,465",66.8%,66.7%,64.0%,2.7%,4.1%,0.1%,22
Michigan,NaN,"8,179,427",61.6%,61.5%,58.7%,2.9%,4.6%,0.1%,23
Minnesota,NaN,"4,579,443",68.0%,67.9%,65.7%,2.2%,3.2%,0.1%,24
Mississippi,NaN,"2,341,292",57.1%,56.5%,53.7%,2.8%,4.9%,0.6%,25
Missouri,NaN,"4,974,792",62.8%,62.4%,60.1%,2.3%,3.7%,0.5%,26
Montana,NaN,"916,289",63.5%,63.0%,61.1%,1.9%,3.0%,0.5%,27
Nebraska,NaN,"1,547,790",68.3%,67.8%,66.2%,1.6%,2.3%,0.5%,28
Nevada,NaN,"2,572,023",63.3%,62.7%,59.3%,3.4%,5.5%,0.6%,29
New Hampshire,NaN,"1,177,400",65.8%,65.7%,64.0%,1.7%,2.5%,0.1%,30
New Jersey,NaN,"7,510,983",66.2%,66.0%,62.7%,3.3%,5.0%,0.2%,31
New Mexico,NaN,"1,710,459",58.5%,57.5%,54.8%,2.8%,4.8%,1.0%,32
New York,NaN,"16,154,241",62.8%,62.6%,59.4%,3.2%,5.1%,0.2%,33
North Carolina,NaN,"8,671,939",62.8%,61.5%,59.2%,2.3%,3.8%,1.3%,34
North Dakota,NaN,"617,710",68.7%,67.6%,66.1%,1.5%,2.2%,1.1%,35
Ohio,NaN,"9,506,533",63.1%,63.0%,60.6%,2.3%,3.7%,0.2%,36
Oklahoma,NaN,"3,178,852",61.0%,60.3%,57.8%,2.5%,4.2%,0.8%,37
Oregon,NaN,"3,509,464",62.4%,62.4%,59.7%,2.7%,4.3%,0.1%,38
Pennsylvania,NaN,"10,660,341",62.8%,62.8%,60.1%,2.7%,4.3%,0.1%,39
Rhode Island,NaN,"916,019",64.6%,64.1%,61.2%,2.9%,4.5%,0.5%,40
South Carolina,NaN,"4,294,594",60.7%,59.7%,57.1%,2.6%,4.4%,1.0%,41
South Dakota,NaN,"716,965",66.9%,66.2%,64.3%,1.9%,2.8%,0.8%,42
Tennessee,NaN,"5,699,603",62.4%,62.0%,59.9%,2.1%,3.4%,0.4%,43
Texas,NaN,"23,471,441",65.5%,65.0%,62.1%,2.9%,4.4%,0.5%,44
Utah,NaN,"2,560,844",70.0%,69.7%,67.8%,1.9%,2.7%,0.3%,45
Vermont,NaN,"548,050",65.0%,64.7%,62.8%,1.8%,2.8%,0.3%,46
Virginia,NaN,"7,041,278",65.3%,63.3%,61.0%,2.3%,3.6%,2.0%,47
Washington,NaN,"6,328,051",64.7%,63.7%,61.1%,2.6%,4.1%,1.0%,48
West Virginia,NaN,"1,466,266",52.8%,52.7%,50.2%,2.5%,4.7%,0.2%,49
Wisconsin,NaN,"4,802,830",65.1%,65.0%,63.2%,1.8%,2.8%,0.1%,50
Wyoming,NaN,"465,883",65.8%,64.9%,62.5%,2.4%,3.8%,0.9%,51

In [14]:
# Save .csv output
out_path = Path("../datasets/filtered_unemployment_data.csv", sep=',', encoding='utf-8', index=False)
unemployment_data_flipped.to_csv(out_path)